- name: Install and Start Nginx
  hosts: ws
  become: true
  vars:
    www_forlder: /var/wwww/html
  tasks:
    - name: Get hostnames
      ansible.builtin.debug:
        var: ansible_hostname
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    - name: Create www/ directory
      ansible.builtin.file:
        path: "{{ www_forlder }}"
        state: directory
        mode: 0755
    - name: Copy the HTML page
      ansible.builtin.template:
        src: ../www/index.html.j2
        dest: "{{ www_forlder }}/index.html"
        mode: 0755
    - name: Copy a new Nginx's configuration
      ansible.builtin.template:
        src: ../nginx/site.com.j2
        dest: /etc/nginx/sites-available/site.com
        mode: 0755
    - name: Create a symbolic link to enable the site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/site.com
        path: /etc/nginx/sites-enabled/default
        state: link
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
