name: Run Playbook 🎉

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  run_playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run playbooks
        run: |
          echo "${{secrets.PRIVATE_KEY}}" >> .ansible_key
          chmod 400 .ansible_key 
          ansible-playbook playbooks/install-nginx.yaml --key-file .ansible_key
          ansible-playbook playbooks/install-loadbalancer.yaml --key-file .ansible_key
