name: Run Playbook 🎉

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/readme.md'

jobs:
  run_playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: install-nginx.yaml
          key: ${{secrets.PRIVATE_KEY}}
